name: Docker Image CI (main)

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-8) docker build . --file Dockerfile -t ghcr.io/$GITHUB_REPOSITORY:$SHORT_SHA -t ghcr.io/$GITHUB_REPOSITORY:main
    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
    - name: Push the Docker image
      run: docker push --all-tags ghcr.io/$GITHUB_REPOSITORY
